name: Build and Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Configure Git
        run: |
          git config --global user.name "Jorge989"
          git remote add origin https://github.com/Jorge989/react-multiples.git
          git checkout master
          git pull origin master
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: dist
          token: ${{ secrets.DEPLOY_TOKEN }}
